version: '2'
services:
    progettoanimeserver-app:
        image: progettoanimeserver
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://progettoanimeserver-mysql:3306/progettoanimeserver?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://progettoanimeserver-elasticsearch:9200
        ports:
            - 8080:8080
    progettoanimeserver-mysql:
        extends:
            file: mysql.yml
            service: progettoanimeserver-mysql
    progettoanimeserver-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: progettoanimeserver-elasticsearch
